// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('Not configured for macos');
      default:
        throw UnsupportedError('Platform not supported');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArDT2BEpBI929JPTNjiM-5AScd-dzNcZg',
    appId: '1:451354106296:web:fa22415059a02537ac174d',
    messagingSenderId: '451354106296',
    projectId: 'date-navigation',
    authDomain: 'date-navigation.firebaseapp.com',
    storageBucket: 'date-navigation.firebasestorage.app',
    measurementId: 'G-555F9DLEST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACAcAJI6psAtIC6XjKLxJvdkxbPvF1leo',
    appId: '1:451354106296:android:bef02b4f801eb79cac174d',
    messagingSenderId: '451354106296',
    projectId: 'date-navigation',
    storageBucket: 'date-navigation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFsF7X0rQkG6UOwLziekpgeKWfL714JvM',
    appId: '1:451354106296:ios:e082379f3ffda418ac174d',
    messagingSenderId: '451354106296',
    projectId: 'date-navigation',
    storageBucket: 'date-navigation.firebasestorage.app',
    iosBundleId: 'com.example.dateNavigation',
  );
}
